---
name: RSSHub
version: 2024.4.1
slug: rsshub
description: Generate a RSS/Atom/JSON feed from anything
url: https://github.com/andrewjswan/rsshub-addon/

codenotary: notary@home-assistant.io

arch: 
  - amd64
  - aarch64
  - armv7

image: ghcr.io/andrewjswan/rsshub-addon-{arch}

startup: services
boot: auto
init: false

ingress: true
ingress_port: 5000

map: 
  - addons:rw
  - all_addon_configs:rw
  - config:rw
  - share:rw
  - ssl:rw

homeassistant: 2024.1.0

panel_icon: mdi:newspaper-variant-multiple
panel_title: RSSHub

ports:
  5000/tcp: 5000

ports_description:
  5000/tcp: "Web Interface"

watchdog: "tcp://[HOST]:[PORT:5000]"
