name: RSSHub / App

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  discussions: write

env:
  IMAGE_NAME: rsshub-addon

jobs:
  changes:
    name: Config / Changed
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.changes.outputs.scr }}
    steps:
      - name: Git Checkout
        uses: actions/checkout@v6

      - name: Check for Changes
        uses: dorny/paths-filter@v4
        id: changes
        with:
          filters: |
            scr:
              - 'rsshub/**'

  init:
    name: Version / Changed
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get-latest-tag.outputs.tag }}
      version: ${{ steps.yaml.outputs.version }}
      architectures: ${{ steps.info.outputs.architectures }}
      description: ${{ steps.desc.outputs.description }}
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - name: Git Checkout
        uses: actions/checkout@v6

      - name: Get Latest Tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
        with:
          semver_only: true

      - name: Get Version from Config
        uses: christian-ci/action-yaml-github-output@v2
        id: yaml
        with:
          file_path: ./rsshub/config.yaml

      - name: Get App Information
        id: info
        uses: home-assistant/actions/helpers/info@master
        with:
          path: "./rsshub"

      - name: Get Description
        id: desc
        run: |
          echo "description="$(cat CHANGELOG.md | awk '/^##/{if(++i>1)exit} i' | awk '{if(NR>1)print}')"" >> $GITHUB_OUTPUT
        working-directory: ./rsshub

      - name: Get build matrix
        id: matrix
        uses: home-assistant/builder/actions/prepare-multi-arch-matrix@2026.03.2
        with:
          architectures: ${{ steps.info.outputs.architectures }}
          image-name: ${{ env.IMAGE_NAME }}

  test:
    name: Test / Build ${{ matrix.arch }}
    if: ${{ needs.changes.outputs.changes == 'true' }}
    needs:
      - changes
      - init
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.init.outputs.matrix) }}
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - name: Git Checkout
        uses: actions/checkout@v6

      - name: Build Test Image
        uses: home-assistant/builder/actions/build-image@2026.03.2
        with:
          arch: ${{ matrix.arch }}
          image: ${{ matrix.image }}
          version: ${{ needs.init.outputs.version }}
          image-tags: |
            ${{ needs.init.outputs.version }}
            latest
          push: false
          cosign: false
          cache-gha: false
          context: ./rsshub
          container-registry-password: ${{ secrets.GITHUB_TOKEN }}

  docker:
    name: Docker
    if: ${{ needs.init.outputs.tag != needs.init.outputs.version }}
    uses: ./.github/workflows/docker.yml
    needs:
      - init
      - test
    permissions:
      contents: read
      packages: write
      id-token: write
    secrets: inherit

  release:
    name: Release
    if: ${{ needs.init.outputs.tag != needs.init.outputs.version }}
    needs:
      - init
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          name: "${{ needs.init.outputs.version }}: RSSHub"
          tag_name: ${{ needs.init.outputs.version }}
          body: ${{ needs.init.outputs.description }}
          generate_release_notes: true
          token: ${{ secrets.DISPATCH_TOKEN }}
